### ISSUE TITLE
您好

### ISSUE THREAD

**Issue by su350380433** [kingcos/cocoapods-backup#2]
这种应用场景广吗，目前好像不大常见。
您这个插件是为了在断网的情况下考虑的吗？或者还有其他的场景吗

**Comment by kingcos** [comment]
@su350380433 

目前来看，场景确实不多。这个插件主要解决我个人在移交部分项目时，需要全源码移交（而 git 仓库并不移交）的痛点。因为当依赖 Pod 较多时，手动需要修改 Podfile 中每个 Pod 为本地路径指向将非常耗费时间。

**Comment by su350380433** [comment]
谢谢
